github: [metadata]
theme: jekyll-theme-slate
title: Mathématiques et informatique pour les BCPST1
description: Documents de mathématiques et d'informatique utiles pour les étudiants de BCPST (Années scolaires 2017-2018 et 2018-2019)
github:
  repository_url: https://github.com/georgejean
lang: fr